name: masal_dunyasi_v1
description: "Masal Dunyasi mobile app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.7.0
  flutter_svg: ^2.2.4
  go_router: ^17.2.2
  provider: ^6.1.5+1
  google_fonts: ^8.0.2
  just_audio: ^0.10.5
  cloud_firestore: ^6.3.0
  shared_preferences: ^2.5.5
  page_flip: ^0.2.5+1
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - "asset/login page/Arkaplan.jpeg"
    - "asset/avatar page/avatar_optimized.jpeg"
    - "asset/home page/"
    - "asset/kategoriler page/"
    - "asset/sleep page/"
    - "asset/profil page/background_optimized.jpg"
    - "asset/profil page/profile_background_optimized.jpg"
    - "asset/rozet page/arkaplan_optimized.jpg"
    - "asset/rozetler/"
    - "asset/audio/"
    - "asset/books/"
    - "asset/icons/"

  fonts:
    - family: BreadMateTR
      fonts:
        - asset: "asset/fonts/Bread mate tr.otf"
